### ISSUE TITLE
Playlist Labels stopped showing up

### ISSUE THREAD

**Issue by ianrispin** [duffey/spicetify-playlist-labels#25]
Spotify version 1.2.34.783.g923721d9
Spicetify version 2.36.4
MacOS 14.2.1

The arrangement of song data repositions to make space for playlist labels (as it always has for me), but the labels are not displaying.
Here is a video of the behavior:
https://github.com/duffey/spicetify-playlist-labels/assets/50210259/ad7d805d-c64e-45c8-ae64-a307d9db7489

An error appeared in the console that seemed to be connected to the issue, but I can't seem to recreate the error in the console (it appeared once and then never again).
Here is a screenshot of the error:
![image](https://github.com/duffey/spicetify-playlist-labels/assets/50210259/85b94e7f-0b78-4393-ac9f-dd78b6c7ea78)

**Comment by CharlieHoldcroft** [comment]
Same started happening to me as well

**Comment by cariosa** [comment]
stopped working for me as well, I tried installing previous release but it doesn't install correctly (the logo doesn't show up in menubar) 
does the update has something to do with it?

**Comment by duffey** [comment]
Sorry guys! Yeah, I updated the extension to cache a bunch of playlist data, but there was a bug which made the cache invalid causing it to never load data again. I just pushed a fix. Please let me know if it works!

**Comment by ianrispin** [comment]
Still not showing up for me. I quit and re-opened spotify, but I'm still having the same issue

**Comment by duffey** [comment]
Hm, well I fixed a bug that occurred when you have over 50 playlists. I thought that was the cause. It seems to be working for me. Can you let me know again if their are any console errors? Also, can you show me what your local storage looks like for the values used by this extension?

![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/a1e60ab9-e388-489d-b619-d323641ac33f)

**Comment by WaddlesPlays** [comment]
My labels stopped working recently as well, here's what I could uncover from DevTools:

Firstly, and this may be a separate issue, I noticed this error in the console whenever the extension is run:
<img width="793" alt="image" src="https://github.com/duffey/spicetify-playlist-labels/assets/45319780/609fe407-2224-4104-a41b-1bb5546b0a01">
Clicking on it took me to this snippet:
<img width="634" alt="image" src="https://github.com/duffey/spicetify-playlist-labels/assets/45319780/be95fed7-5a9d-4146-9b77-57fd6fc73e5a">
Seeing that c seemed to be a collection of liked songs, I figured this error may have been related to my lack of liked songs. To test, I liked a song and reloaded Spotify, which resolved the error and threw this error instead:
<img width="810" alt="image" src="https://github.com/duffey/spicetify-playlist-labels/assets/45319780/c9722c69-b496-4359-b703-6009e60db846">
which leaves my local storage missing a few values when compared to your screenshot:
<img width="635" alt="image" src="https://github.com/duffey/spicetify-playlist-labels/assets/45319780/be73224c-3482-4e2e-b9a6-1599b1c79f61">
And, of course, the labels don't populate (although the divs for them are there)

Here's my spicetify version info in case that proves useful:
Spotify for macOS (Apple Silicon)
1.2.35.663.gb699649e
Spicetify v2.36.4
Theme: Sleek / CatppuccinMocha
Extensions: oldCoverClick.js, shuffle+.js, fullScreenWrapper.js, volume-profiles.js, QueueTime.js, playlist-icons.js, volumePercentage.js, LuckyLP.js, power-bar.js, cat-jam.js, spicetify-playlist-labels.js
Custom apps: marketplace, lyrics-plus, new-releases
xpui_2024-04-05_1712324573103_b699649
cef_122.1.13+gde5b724+chromium-122.0.6261.130
Runtime: Chrome
All of my extensions are from marketplace, and my MacOS version is 14.4.1

**Comment by ianrispin** [comment]
These are the values for me
<img width="801" alt="image" src="https://github.com/duffey/spicetify-playlist-labels/assets/50210259/b03bbd15-95cc-4df8-8ddb-09833f84fabf">

**Comment by duffey** [comment]
@WaddlesPlays It seems that liking a song avoided one bug and then you experienced a different bug where you have so many playlists that it can't fit them all in local storage. I didn't think of this, so I will see if caching is still possible or what I should do.

**Comment by SirSragus** [comment]
Perhaps that was part of my original issue as well, I have a lot of playlists.

**Comment by WaddlesPlays** [comment]
> It seems that liking a song avoided one bug and then you experienced a different bug where you have so many playlists that it can't fit them all in local storage. I didn't think of this, so I will see if caching is still possible or what I should do.

I see! Should I file a separate issue for the liked songs bug?

**Comment by duffey** [comment]
@WaddlesPlays Is it still occurring? If it is, I would appreciate that as well as the output of the following in the dev console. I would rather not unlike all my songs to find out!

```js
await Spicetify.Platform.LibraryAPI.getTracks({ limit: Number.MAX_SAFE_INTEGER });
```

**Comment by WaddlesPlays** [comment]
The rollback commits seemed to have fixed it, labels now display and I don't see the error in my console anymore. I think it just took marketplace a bit to catch up! If the commits ever happened to be reintroduced, the fix is probably a simple null-check or something. Thanks!

**Comment by ianrispin** [comment]
This is still an issue for me, but there's a different error showing up in the console:
![image](https://github.com/duffey/spicetify-playlist-labels/assets/50210259/355e7926-671c-4447-bd77-9a218915570f)

**Comment by duffey** [comment]
@ianrispin That error comes from xpui.js so I think it's unrelated, however someone else mentioned the labels aren't showing up for them. If you catch any other errors where it says spicetify-playlist-labels.js please let me know. I will try to find the cause on my Spotify in the meantime.

**Comment by D3SOX** [comment]
![image](https://github.com/duffey/spicetify-playlist-labels/assets/24937357/be5fb94d-4a5a-464d-bca6-3bdfd424b242)
I get this error with Spotify v1.2.11.916 Spicetify v2.34.1

**Comment by duffey** [comment]
@User094573 Please let me know if there are any errors related to playlist labels in the dev console, or any steps I might follow to reproduce the issue.

**Comment by cariosa** [comment]
Same issue for me, I tried fully uninstalling spicetify and reinstalling it, then it shows up after installing the extension freshly but fails after reloading or restarting. I'm using the old version for the time being but it is not snappy.

**Comment by User094573** [comment]
@duffey, I just checked it on my Windows machine and the playlist labels are working fine too. I haven't done anything to change this, it's simply working as expected since I started Spotify.

**Comment by duffey** [comment]
@User094573 Thanks for letting me know. It might be due to the bugfix I pushed the other day.

**Comment by duffey** [comment]
@ianrispin Can you let me know if the labels are showing for you now?

**Comment by D3SOX** [comment]
For me it currently only shows one playlist (which is always Liked Songs if liked) with ellipsis left to it and no possibility to see the others

**Comment by ianrispin** [comment]
@duffey Yeah, it's showing liked songs as well as _some_ of my playlists, but not nearly all of them.

**Comment by cariosa** [comment]
If anyone's still facing the problem, I got it working by reloading spotify (through installing or uninstalling some unwanted extension). So for me this extension doesn't load at first boot.

**Comment by SydneyNS** [comment]
> If anyone's still facing the problem, I got it working by reloading spotify (through installing or uninstalling some unwanted extension). So for me this extension doesn't load at first boot.

Well, that WAS working on and off, but it seems I can't get the label icons to load no matter what I do now. Reinstall old spotify? Nope, doesn't work. reload spotify? Nope. Unliking my entire library? Nope. Reliking anything from my library? Nope. Reinstalling and uninstalling all extensions? Nope. This extension is completely broken.

I also don't get why it is broken, when I first started using this extension, it worked fine, even though I had over 8k songs in my library and way more playlists than I do now.
